# @package _group_
env: "duckietown_gym_env"  # used to set the hydra dir, ignored otherwise

# These settings are based on the cheetah run yaml file

# General configuration overrides
trial_length: 250
action_noise_std: 0.3

# Model overrides
num_grad_updates: 100
sequence_length: 50
batch_size: 50
free_nats: 3
kl_scale: 1.0

# Planner configuration overrides
planning_horizon: 12
cem_num_iters: 10
cem_elite_ratio: 0.1
cem_population_size: 1000
cem_alpha: 0.0
cem_clipped_normal: true

#Ali's overrides
model_learning_rate: 1e-4
